#!/bin/bash
contigs=$1
name=`echo $contigs | sed 's/.db//'`
anvi-export-gene-calls -c $contigs -o ${name}.gene_calls.txt
anvi-get-sequences-for-gene-calls -c $contigs --get-aa-sequences -o ${name}.proteins.txt
python /LAB_DATA/DATABASES/dbCAN_meta_server/anvi-script-convert-genecalls-to-gff.py ${name}.gene_calls.txt
python /LAB_DATA/DATABASES/dbCAN_meta_server/run_dbcan.py --cluster --gff ${name}.gene_calls.txt --out_dir ${name} --out_pre ${name}_ ${name}.proteins.txt protein
python /LAB_DATA/DATABASES/dbCAN_meta_server/generate_dbCAN_consensus_and_counts.py ${name} --out_pre ${name}_ --min_tools 2
python /LAB_DATA/DATABASES/dbCAN_meta_server/anvi-script-convert-dbCAN-to-functions.py ${name} --out_pre ${name}_
anvi-import-functions -c $contigs -i ${name}/${name}_dbcan_functions_default.txt
